"""Datasets for the explainers that are not pathology simulations.

Each build_* function runs a seeded simulation on the engine and returns
JSON-serializable data plus the numbers the explainer quotes. Regenerated by
scripts/regenerate_figures.py alongside the pathology data.
"""

from typing import Any

import numpy as np

from lab.assignment import assign_users
from lab.populations import continuous_users, draw_continuous, zero_inflated_users
from lab.stats import (
    cuped_t_test,
    mann_whitney_u_test,
    minimum_detectable_effect,
    power_two_sample,
    welch_t_test,
)


def build_randomization(*, seed: int = 21) -> dict[str, Any]:
    """Self-selection versus randomization on the same population.

    Adoption probability rises with the user's latent baseline (power users
    adopt), so the observational adopter-versus-non-adopter comparison bakes
    selection into the estimate. Randomized assignment on the same users
    recovers the truth. The expected observational estimate is computed
    exactly from the latent baselines.
    """
    rng = np.random.default_rng(seed)
    effect = 0.5
    users = continuous_users(100_000, seed=seed)
    baseline = users["user_mean"].to_numpy()

    # P(adopt) linear in baseline rank, mean 0.4: rank 0 -> 0.1, rank 1 -> 0.7.
    u = baseline.argsort().argsort() / (len(users) - 1)
    p_adopt = 0.1 + 0.6 * u
    adopted = rng.random(len(users)) < p_adopt
    y_obs = baseline + effect * adopted + rng.normal(0.0, 5.0, len(users))
    observational = welch_t_test(y_obs[adopted], y_obs[~adopted]).estimate
    expected_observational = effect + baseline[adopted].mean() - baseline[~adopted].mean()

    treated = assign_users(users, seed=seed + 1)
    y_rct = draw_continuous(users, treated, effect=effect, seed=seed + 2)
    randomized = welch_t_test(y_rct[treated], y_rct[~treated]).estimate

    return {
        "true_effect": effect,
        "observational": round(float(observational), 3),
        "expected_observational": round(float(expected_observational), 3),
        "randomized": round(float(randomized), 3),
        "selection_bias": round(float(expected_observational - effect), 3),
    }


def build_test_choice(*, seed: int = 22) -> dict[str, Any]:
    """Metric shapes, and measured power of Welch t versus Mann-Whitney on
    the zero-inflated one.

    The treatment multiplies an active user's spend by 1.25 and leaves
    activity unchanged. Both tests run on the same 200 simulated experiments
    (20,000 users per arm). Mann-Whitney loses here by design of the truth:
    70% of users are zeros in both arms (pure ties, no rank signal), so a
    spend-scaling effect moves the mean far more than the rank distribution.
    """
    rng = np.random.default_rng(seed)

    def hist(values: np.ndarray, bins: int, range_: tuple[float, float]) -> dict[str, list[float]]:
        counts, edges = np.histogram(values, bins=bins, range=range_, density=True)
        return {"edges": [round(float(e), 3) for e in edges],
                "density": [round(float(c), 5) for c in counts]}

    continuous = rng.normal(10.0, np.sqrt(29.0), 30_000)
    zi_users = zero_inflated_users(30_000, seed=seed)
    zero_inflated = zi_users["pre_metric"].to_numpy()

    n_sims, n_per_arm, multiplier = 200, 20_000, 1.25
    rejections_t, rejections_mw = 0, 0
    for sim in range(n_sims):
        pop = zero_inflated_users(2 * n_per_arm, seed=1000 + sim)
        srng = np.random.default_rng(5000 + sim)
        active = srng.binomial(1, pop["p_active"].to_numpy())
        spend = srng.lognormal(1.0, 1.0, len(pop))
        treated = np.arange(len(pop)) < n_per_arm
        y = active * spend * np.where(treated, multiplier, 1.0)
        rejections_t += welch_t_test(y[treated], y[~treated]).significant()
        rejections_mw += mann_whitney_u_test(y[treated], y[~treated]).significant()

    return {
        "distributions": {
            "continuous": hist(continuous, 40, (-8.0, 28.0)),
            "binary": {"rate": 0.10},
            "zero_inflated": hist(np.clip(zero_inflated, 0, 30), 40, (0.0, 30.0)),
        },
        "zero_share": round(float((zero_inflated == 0).mean()), 3),
        "spend_multiplier": multiplier,
        "n_per_arm": n_per_arm,
        "n_sims": n_sims,
        "power_welch": round(rejections_t / n_sims, 3),
        "power_mann_whitney": round(rejections_mw / n_sims, 3),
    }


def build_cuped(*, seed: int = 23) -> dict[str, Any]:
    """The engine-walkthrough CUPED setting: 28-day pre-period covariate.

    Exports a point sample for the scatter, the exact analytic variance
    reduction, and the measured CI widths.
    """
    b, w, k = 3.0, 3.0, 28
    users = continuous_users(100_000, between_sd=b, within_sd=w, pre_period_days=k, seed=seed)
    treated = assign_users(users, seed=seed + 1)
    y = draw_continuous(users, treated, effect=0.2, within_sd=w, seed=seed + 2)
    raw = welch_t_test(y[treated], y[~treated])
    cuped = cuped_t_test(
        y[treated], users["pre_metric"][treated], y[~treated], users["pre_metric"][~treated]
    )
    rho = b**2 / (np.sqrt(b**2 + w**2 / k) * np.sqrt(b**2 + w**2))

    idx = np.random.default_rng(seed + 3).choice(len(users), 700, replace=False)
    return {
        "scatter": {
            "pre": [round(float(v), 2) for v in users["pre_metric"].to_numpy()[idx]],
            "post": [round(float(v), 2) for v in y[idx]],
            "treated": [bool(t) for t in treated[idx]],
        },
        "theta": round(float(cuped.theta), 3),
        "analytic_rho_sq": round(float(rho**2), 3),
        "variance_reduction": round(float(cuped.variance_reduction), 3),
        "raw_ci_width": round(float(raw.ci_high - raw.ci_low), 4),
        "cuped_ci_width": round(float(cuped.test.ci_high - cuped.test.ci_low), 4),
        "true_effect": 0.2,
    }


def build_power_curves(*, seed: int = 24) -> dict[str, Any]:
    """Power versus sample size, and MDE versus runtime, for a 10% signup rate.

    Pure calculator output (validated against statsmodels in the unit tests);
    no Monte Carlo needed.
    """
    sd = float(np.sqrt(0.10 * 0.90))
    n_grid = [int(n) for n in np.geomspace(1_000, 200_000, 40)]
    lifts = [0.005, 0.010, 0.020]
    curves = {
        f"{lift:.3f}": [round(power_two_sample(n, effect=lift, sd=sd), 4) for n in n_grid]
        for lift in lifts
    }
    users_per_day = 2_500
    days = list(range(1, 57))
    mde = [
        round(minimum_detectable_effect(users_per_day * d, sd=sd), 5) for d in days
    ]
    return {
        "baseline_rate": 0.10,
        "n_per_arm": n_grid,
        "curves": curves,
        "users_per_day_per_arm": users_per_day,
        "days": days,
        "mde_by_day": mde,
    }
